<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FinanceHub.ItauIntegration.Domain\FinanceHub.ItauIntegration.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\FinanceHub.Shared.Messaging\FinanceHub.Shared.Messaging.csproj" />
    <ProjectReference Include="..\..\..\Shared\FinanceHub.Shared.Certificates\FinanceHub.Shared.Certificates.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
